package dao.dao_implementations.jdbc.utils;

public class SqlQueries {
    public static final String SELECT_ITEM_BY_ID = "SELECT * FROM ITEMS WHERE ID_ITEM = ?";
    public static final String SELECT_ALL_ITEM = "SELECT * FROM ITEMS";
    public static final String INSERT_ITEMS = "INSERT INTO ITEMS (NAME, COMPANY, PRICE) VALUES (?,?,?)";
    public static final String UPDATE_ITEM = "UPDATE ITEMS SET NAME  = ?, COMPANY = ?, PRICE = ? WHERE ID_ITEM = ?";
    public static final String DELETE_ITEM = "DELETE FROM ITEMS WHERE ID_ITEM = ?";


    public static final String SELECT_CUSTOMER_BY_ID = "SELECT * FROM CUSTOMERS WHERE ID_CUSTOMER = ?";
    public static final String SELECT_ALL_CUSTOMERS = "SELECT * FROM CUSTOMERS";
    public static final String INSERT_CUSTOMERS = "INSERT INTO CUSTOMERS (NAME, TELEPHONE, ADDRESS) VALUES (?, ?, ?)";
    public static final String UPDATE_CUSTOMER = "UPDATE CUSTOMERS SET NAME  = ?, TELEPHONE = ?, ADDRESS = ? WHERE ID_CUSTOMER = ?";
    public static final String DELETE_CUSTOMER = "DELETE FROM CUSTOMERS WHERE ID_CUSTOMER = ?";

    public static final String SELECT_PURCHASE_BY_ID = "SELECT PURCHASES.ID_PURCHASE, PURCHASES.DATE, CUSTOMERS.ID_CUSTOMER, CUSTOMERS.NAME, CUSTOMERS.TELEPHONE, CUSTOMERS.ADDRESS,ITEMS.ID_ITEM, ITEMS.NAME, ITEMS.COMPANY, ITEMS.PRICE FROM ((PURCHASES JOIN CUSTOMERS ON PURCHASES.ID_CUSTOMER = CUSTOMERS.ID_CUSTOMER) JOIN ITEMS ON PURCHASES.ID_ITEM = ITEMS.ID_ITEM) WHERE ID_PURCHASE = ? ORDER BY PURCHASES.ID_PURCHASE";
    public static final String SELECT_ALL_PURCHASES = "SELECT PURCHASES.ID_PURCHASE, PURCHASES.DATE, CUSTOMERS.ID_CUSTOMER, CUSTOMERS.NAME, CUSTOMERS.TELEPHONE, CUSTOMERS.ADDRESS,ITEMS.ID_ITEM, ITEMS.NAME, ITEMS.COMPANY, ITEMS.PRICE FROM ((PURCHASES JOIN CUSTOMERS ON PURCHASES.ID_CUSTOMER = CUSTOMERS.ID_CUSTOMER) JOIN ITEMS ON PURCHASES.ID_ITEM = ITEMS.ID_ITEM) ORDER BY PURCHASES.ID_PURCHASE";
    public static final String INSERT_PURCHASE = "INSERT INTO PURCHASES (DATE, ID_CUSTOMER, ID_ITEM) VALUES (?, ?, ?)";
    public static final String UPDATE_PURCHASE = "UPDATE PURCHASES SET DATE  = ?, ID_CUSTOMER = ?, ID_ITEM = ? WHERE ID_PURCHASE = ?";
    public static final String DELETE_PURCHASE = "DELETE FROM PURCHASES WHERE ID_PURCHASE = ?";
    public static final String SELECT_ALL_PURCHASES_BY_CUSTOMER = "SELECT PURCHASES.ID_PURCHASE, PURCHASES.DATE, CUSTOMERS.ID_CUSTOMER, CUSTOMERS.NAME, CUSTOMERS.TELEPHONE, CUSTOMERS.ADDRESS,ITEMS.ID_ITEM, ITEMS.NAME, ITEMS.COMPANY, ITEMS.PRICE FROM ((PURCHASES JOIN CUSTOMERS ON PURCHASES.ID_CUSTOMER = CUSTOMERS.ID_CUSTOMER AND CUSTOMERS.ID_CUSTOMER = ?) JOIN ITEMS ON PURCHASES.ID_ITEM = ITEMS.ID_ITEM)";
    public static final String DELETE_PURCHASE_BY_CUSTOMER = "DELETE FROM PURCHASES WHERE ID_CUSTOMER = ?";
    public static final String DELETE_PURCHASE_BY_ITEM = "DELETE FROM PURCHASES WHERE ID_ITEM = ?";
}
